spring:
  application:
    name: "configserver"

  profiles:
    active: "native"

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

  cloud:
    config:
      server:
        bootstrap: true
        composite:
          - type: native
            search-locations: "classpath:config"

server:
  port: 8071

encrypt:
  key: "12345678901234567890123456789012"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}


logging:
  level:
    com:
      eazybytes:
        cards: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"


