spring:
  application:
    name: "configserver"

  profiles:
    active: "native"

  cloud:
    config:
      server:
        bootstrap: true
        composite:
          - type: native
            search-locations: "classpath:config"

server:
  port: 8071
